name: Lint and Test
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python

on:
  pull_request:
  push:
  schedule:
      - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]
        # python-version: [3.7, 3.8, 3.9]
        # os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        make install
    - name: Lint with flake8
      run: |
        flake8 Work
    - name: Lint with pylint
      run: |
        pylint Work 
    - name: Lint docs with Pydocstyle
      run: |
        pydocstyle Work 
    - name: Check type annotations with Mypy 
      run: |
        mypy Work 
    - name: Test with pytest
      run: pytest
    # - name: Test with tox
    #   run: tox -e py
